# Model configurations
models:
  llama3-70b-8192:
    name: Llama3-70b-chat
    provider: groq
    tokens: 8192
    developer: Meta
    description: Llama3-70b-chat is a large language model developed by Meta, known for its strong performance on various natural language processing tasks.

# Default maximum tokens for response generation
default_max_tokens: 8192
